### PR TITLE
Test UIWindow?? for double optional

### PR DESCRIPTION
**Pull request by marcotta**

### CODE REVIEW

**Comment by darwin-morocho** [comment]
@marcotta  why this change is need it?

**Comment by marcotta** [comment]
@darwin-morocho 
`if let applicationWindow = UIApplication.shared.delegate?.window` 
`UIApplication.shared.delegate?.window` is an `optional UIWindow?`
This makes it a double optional `UIWindow??`
For this reason when applicationWindow is nil it will return nil and never get to the UIScenes flow.

**Comment by darwin-morocho** [comment]
I will use the next solution
```
        let applicationWindow = UIApplication.shared.delegate?.window
        if applicationWindow != nil {
            return applicationWindow!!
        }
        
```

**Comment by marcotta** [comment]
Just tested it and it fails, see attached screenshot

Screenshot 2021-11-03 at 22 54 06

**Comment by darwin-morocho** [comment]
I will try your solution

**Comment by darwin-morocho** [comment]
@marcotta  I have used your code in the last release

**Pull request closed without merging**
