### PR TITLE
Migrated to null safety

### PR DESCRIPTION
**Pull request by sam-markoe**
Migrated the package to null safety using `dart migrate`.

Bumped the version number to indicate a breaking change, and upped the minimum SDK version for the package. Additionally removed some unnecessary type declarations. I also removed a couple of packages that aren't available for null safety, but were only used in the `example`.

I also renamed `isLogged` to `accessToken`, since `isLogged` implies that it returns a boolean value, which it does not. See the [Effective Dart style guide](https://dart.dev/guides/language/effective-dart/design#prefer-a-noun-phrase-for-a-non-boolean-property-or-variable) for rationale behind why I did this.

### CODE REVIEW

**Comment by Nolence** [comment]
Hi ! this was merged into null-safety branch but I don't think it's been published to pub as a pre-release yet? Is there still testing going on or can this be made public

**Comment by darwin-morocho** [comment]
@Nolence I've been working in this branch to test it. At the moment I don't have much time to do this for that reason this version is not published yet

**Comment by samlythemanly** [comment]
@darwin-morocho You can publish the package as prerelease so that anyone who wants to use null safety may do so.

See https://dart.dev/tools/pub/publishing#publishing-prereleases

**Comment by Theunodb** [comment]
We are willing to assist with the testing if you can drop it in pre-release

**Comment by darwin-morocho** [comment]
hi @samlythemanly , @Theunodb, @Nolence  thanks for your help.  This plugin was published as a pre-release version on pub.dev

**Pull request merged**
